[package]
name = "imgresize"
version = "0.1.0"
authors = ["荒野無燈 <i@80x86.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.4"
glob = "0.3.2"